### ISSUE TITLE
Needs a name

### ISSUE THREAD

**Issue by richfitz** [richfitz/datastorr#1]
Dataverse is taken already: http://dataverse.org

Ideas for a new name @wcornwell, @mwpennell?

**Comment by mwpennell** [comment]
Could riff off storr (a name I like) and call it datastorr

**Comment by wcornwell** [comment]
dataversion?

**Comment by mwpennell** [comment]
reminds me a bit too much of subversion...

**Comment by richfitz** [comment]
(also cc: @dfalster)

**Comment by wcornwell** [comment]
Can't let the crappiness of subversion ruin the word "version" forever...

**Comment by richfitz** [comment]
Subversion is _very_ crappy.

**Comment by mwpennell** [comment]
since it is largely git based you can play off this: (e.g., gitdat or
octodat)

**Comment by dfalster** [comment]
`dataversion` seems pretty good. Otherwise could play on temporal theme with
`datamachine`, `timemachine`. Or more plays on github: `ghrelease`, `githubreleases`.

**Comment by mwpennell** [comment]
a key for a good name is that is must be findable via google search (i.e.,
it must be different enough from common search terms to be found; brian
o'meara told me he greatly regretted calling his package "brownie")

**Comment by dfalster** [comment]
Good point, that would definitely rule out some of my suggestions above. 
Some more possibilities i thought of: datashower, dataflurry, datarush, datastack, datadrop.
Though all have _some_ competing traffic under the Omeara google test.

**Comment by richfitz** [comment]
Probably names that have 'dat' in the are out, to avoid confusion with http://dat-data.com/

Googleability is key, though in this case it might be somewhat less important than usual.  This will only be used by data providers and transparent to users, so the potential pool of people is pretty low.

Given that I think the whole thing would (and eventually should) work pretty happily without github probably worth avoiding that too...

Dirk suggested datasong (as in not dataverse).  I will keep ruminating; there's no rush until we start publicising.

**Comment by mwpennell** [comment]
I like datasong

**Comment by richfitz** [comment]
Says the man who claims he doesn't like puns

**Comment by wcornwell** [comment]
Another idea: livingdata

**Comment by richfitz** [comment]
livingdata is nice, Will.  Captures what we're trying to do and matches what we've been calling it internally.

**Comment by richfitz** [comment]
In the end: datastorr.
