### ISSUE TITLE
Autogenerated metadata help files

### ISSUE THREAD

**Issue by noamross** [richfitz/datastorr#3]
A nice-to-have, perhaps.  It would be great if metadata and/or data descriptions could have auto-generated help files, so that `?my_data()` would call these up in R-help.  Of course, one can write help files, but in the spirit of not repeating oneself, it would be good to have a way to ingest metadata files and generate help files with these.

**Comment by richfitz** [comment]
I think this is implemented already?  The help files in [datastorr.example](https://github.com/richfitz/datastorr.example) are generated (via roxygen) with the [autogenerate](https://github.com/richfitz/datastorr/blob/master/R/autogenerate.R#L60) function.

Or was there some other help files that need autogenerating?  I was imagining that the skeleton of the package would be autogenerated and then additional information would be added by hand (see [taxonlookup](https://github.com/traitecoevo/taxonlookup) for an example of our approach there).

But this is totally experimental at this point so I'm very keen to understand alternative use-cases.

**Comment by noamross** [comment]
I think I need to work through our whole use-case to see what is and is not implemented.  I'll close for now, but I should be able to give  usability report (me making a package, and some colleagues using the data) before the end of the year.

**Comment by richfitz** [comment]
OK, keep me in the loop (though I'll be away over the break).

In the absence of decent docs, I'd recommend looking at the [tests here](https://github.com/richfitz/datastorr/blob/master/tests/testthat/test-github-releases.R#L53) (sorry) for seeing how to make releases from R.
